/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package mainpage;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author Zirco
 */
public class MemberSearch extends javax.swing.JFrame {

        Connection con;
        Statement stmt;
        Statement pst ;
       
        ResultSet rs;
        int curRow = 0;

    public MemberSearch() {
        initComponents();
        setSize(700,400);
        setResizable(false);
        setTitle("Search");
        DBConnect();
        jSeparatorOne.setVisible(false);
        jSeparatortwo.setVisible(false);
        jSeparatorthree.setVisible(false);
        jSeparatorfour.setVisible(false);
        jLabelName.setVisible(false);
        jLabelAuthor.setVisible(false);
    }
      public void DBConnect(){
        try{
        String host = "jdbc:mysql://localhost:3306/booksdb";
        
        String db_uname = "root";
        String db_pass = "";
        con = DriverManager.getConnection(host, db_uname, db_pass);
        stmt = con.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE, ResultSet.CONCUR_UPDATABLE);
        String sql = "SELECT * FROM books";
        rs = stmt.executeQuery(sql);
        rs.next();
        
        
        
        //default valuse to input
       //adminId.setText("");
       //adminPass.setText("");
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(MemberSearch.this, err.getMessage());
        }
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        bookone = new javax.swing.JLabel();
        bookthree = new javax.swing.JLabel();
        booktwo = new javax.swing.JLabel();
        bookfour = new javax.swing.JLabel();
        bookfive = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparatorOne = new javax.swing.JSeparator();
        jSeparatortwo = new javax.swing.JSeparator();
        jSeparatorthree = new javax.swing.JSeparator();
        jSeparatorfour = new javax.swing.JSeparator();
        jLabelName = new javax.swing.JLabel();
        jLabelAuthor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setMinimumSize(new java.awt.Dimension(700, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 58, 540, 14));

        jLabel1.setBackground(new java.awt.Color(153, 153, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 153, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpage/search.png"))); // NOI18N
        jLabel1.setText("Search");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 100, 29));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Search :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, 67, 26));
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 210, 220, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpage/backdsnd.png"))); // NOI18N
        jButton1.setText("  Search");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 240, 120, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 130, 210, 25));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 210, 25));
        getContentPane().add(bookone, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 121, 24));
        getContentPane().add(bookthree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, 121, 24));
        getContentPane().add(booktwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 121, 24));
        getContentPane().add(bookfour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 121, 24));
        getContentPane().add(bookfive, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 121, 24));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 255));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainpage/seaarch hisotry.png"))); // NOI18N
        jLabel5.setText("  Search hisotry");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 150, 35));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 160, 10));
        getContentPane().add(jSeparatorOne, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 173, 10));
        getContentPane().add(jSeparatortwo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 173, 10));
        getContentPane().add(jSeparatorthree, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 250, 173, 10));
        getContentPane().add(jSeparatorfour, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 290, 173, 10));

        jLabelName.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelName.setText("Name :");
        getContentPane().add(jLabelName, new org.netbeans.lib.awtextra.AbsoluteConstraints(344, 130, 50, 20));

        jLabelAuthor.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelAuthor.setText("Author :");
        getContentPane().add(jLabelAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(334, 160, 60, 20));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
               try {
        String query = "select * from books where Title = ? ";
        PreparedStatement pst = con.prepareStatement(query);
        pst.setString(1, jTextField1.getText());
        rs=pst.executeQuery();
        if (rs.next()){
            String add1 =rs.getString("Title");
            String add2 =rs.getString("Author");
            jLabelName.setVisible(true);
            jLabelAuthor.setVisible(true);
            jLabel3.setText(add1);
            jLabel4.setText(add2) ;
            historycheck(add1); 
        }
        else{
            JOptionPane.showMessageDialog(null, "not found");
            jLabel3.setText(" ");
            jLabel4.setText(" ") ;
            jLabelName.setVisible(false);
            jLabelAuthor.setVisible(false);
            }
        }
        catch(SQLException err){
            JOptionPane.showMessageDialog(MemberSearch.this, err.getMessage());
        }
  
    }//GEN-LAST:event_jButton1ActionPerformed

    public void historycheck(String add1 ){
            String histCheckerOne = bookone.getText();
            String histCheckertwo = booktwo.getText();
            String histCheckerthree = bookthree.getText();
            String histCheckerfour = bookfour.getText();
            String histCheckerfive = bookfive.getText();
            if (histCheckerOne==""){
                bookone.setText(add1);
            }
            else if(histCheckertwo==""){
                jSeparatorOne.setVisible(true);
                booktwo.setText(bookone.getText());
                bookone.setText(add1);
            }
            else if(histCheckerthree==""){
                jSeparatortwo.setVisible(true);
                bookthree.setText(booktwo.getText());
                booktwo.setText(bookone.getText());
                bookone.setText(add1);
            }
            else if(histCheckerfour==""){
                jSeparatorthree.setVisible(true);
                bookfour.setText(bookthree.getText());
                bookthree.setText(booktwo.getText());
                booktwo.setText(bookone.getText());
                bookone.setText(add1);
            }
            else if(histCheckerfive==""){
                jSeparatorfour.setVisible(true);
                bookfive.setText(bookfour.getText());
                bookfour.setText(bookthree.getText());
                bookthree.setText(booktwo.getText());
                booktwo.setText(bookone.getText());
                bookone.setText(add1);
            }
            else{
                bookfive.setText(bookfour.getText());
                bookfour.setText(bookthree.getText());
                bookthree.setText(booktwo.getText());
                booktwo.setText(bookone.getText());
                bookone.setText(add1);
            }
    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MemberSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MemberSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MemberSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MemberSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MemberSearch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bookfive;
    private javax.swing.JLabel bookfour;
    private javax.swing.JLabel bookone;
    private javax.swing.JLabel bookthree;
    private javax.swing.JLabel booktwo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabelAuthor;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparatorOne;
    private javax.swing.JSeparator jSeparatorfour;
    private javax.swing.JSeparator jSeparatorthree;
    private javax.swing.JSeparator jSeparatortwo;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
